name: Brakeman

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Brakeman
      uses: devmasx/brakeman-linter-action@v1.0.0
      with:
        exit_on_failure: true
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
